"use client";

import React, { useState } from "react";
import { useProjectStore } from "@/store/project-store";
import { RefreshCw, ExternalLink, FileCode, Code2, Download, Rocket, Share2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { ScrollArea } from "@/components/ui/scroll-area";
import { cn } from "@/lib/utils";
import { SandpackProvider, SandpackLayout, SandpackPreview } from "@codesandbox/sandpack-react";
import JSZip from "jszip";
import { saveAs } from "file-saver";
import { toast } from "sonner";

export function PreviewPanel() {
  const { previewUrl, generatedFiles, projectName } = useProjectStore();
  const [key, setKey] = useState(0);
  const [selectedFile, setSelectedFile] = useState<string | null>(null);
  const [viewMode, setViewMode] = useState<"preview" | "code">("code");
  const [isDeploying, setIsDeploying] = useState(false);

  const handleRefresh = () => {
    setKey(prev => prev + 1);
  };

  const handleDownload = async () => {
    if (!generatedFiles || generatedFiles.length === 0) {
        toast.error("No files to download.");
        return;
    }

    try {
        const zip = new JSZip();
        
        // Add all generated files to the zip
        generatedFiles.forEach((file: any) => {
            // Remove leading slash if present
            const path = file.path.startsWith('/') ? file.path.substring(1) : file.path;
            zip.file(path, file.content);
        });

        // Add a basic README
        zip.file("README.md", `# ${projectName || "Project"}\n\nGenerated by Superior AI.\n\n## Getting Started\n\n1. Run \`npm install\`\n2. Run \`npm run dev\`\n`);

        const content = await zip.generateAsync({ type: "blob" });
        saveAs(content, `${projectName?.replace(/\s+/g, '-').toLowerCase() || "project"}.zip`);
        toast.success("Project downloaded successfully!");
    } catch (error) {
        console.error("Download failed:", error);
        toast.error("Failed to create zip file.");
    }
  };

  const handleDeploy = async () => {
    setIsDeploying(true);
    
    // "Real" Deployment Flow for a Client-Side App:
    // 1. Download the code (so user has it)
    // 2. Open Vercel Import page (so user can deploy it)
    
    toast.info("Preparing for deployment...");
    
    try {
        await handleDownload(); // Auto-download first
        
        setTimeout(() => {
            setIsDeploying(false);
            toast("🚀 Ready to Deploy!", {
                description: "Source code downloaded. Upload to Vercel to go live.",
                action: {
                    label: "Open Vercel",
                    onClick: () => window.open("https://vercel.com/new", "_blank"),
                },
                duration: 10000,
            });
        }, 1500);
    } catch (e) {
        setIsDeploying(false);
        toast.error("Deployment preparation failed.");
    }
  };

  const handleExternalLink = () => {
     // If using Sandpack, we can't easily "open external" without CodeSandbox.
     // But we can trigger the native Sandpack "Open in CodeSandbox" if we enable it, 
     // or just show a toast explaining.
     if (previewUrl && previewUrl !== "sandpack") {
         window.open(previewUrl, "_blank");
     } else {
        toast.info("Click the 'Open in CodeSandbox' icon inside the preview to edit externally.");
     }
  };

  const hasFiles = generatedFiles && Array.isArray(generatedFiles) && generatedFiles.length > 0;
  
  // Select first file by default if none selected
  React.useEffect(() => {
    if (hasFiles && !selectedFile) {
        const pageFile = generatedFiles.find((f: any) => f?.path?.includes("page.tsx")) || generatedFiles[0];
        if (pageFile && pageFile.path) {
            setSelectedFile(pageFile.path);
        }
    }
    // Auto-switch to preview if previewUrl is set (even if "sandpack"), otherwise default to code
    if (!previewUrl && hasFiles && viewMode === "preview") {
        // Allow staying in preview if we have files (Sandpack mode)
    } else if (!previewUrl && hasFiles && viewMode !== "preview") {
         // Don't auto-switch to code if we have files, let user choose
    }
  }, [hasFiles, selectedFile, generatedFiles, previewUrl, viewMode]);

  // ERROR BOUNDARY FOR PREVIEW
  // Sandpack can throw errors that crash the whole React app. We need a way to catch them.
  // Since we can't easily wrap Sandpack in an ErrorBoundary inside a hook, we rely on Sandpack's own error handling.
  // But we can ensure we don't pass bad props.

  const selectedFileContent = generatedFiles?.find((f: any) => f?.path === selectedFile)?.content || "";
  const canPreview = !!(previewUrl || hasFiles);

  // Prepare files for Sandpack
  const sandpackFiles = React.useMemo(() => {
    if (!hasFiles) return {};
    
    try {
        const files: Record<string, string> = {};
        
        // Add all generated files
        generatedFiles.forEach((file: any) => {
            if (!file || !file.path) return;
            
            // SKIP package.json from the preview environment.
            if (file.path.endsWith("package.json")) return;

            // Ensure path starts with /
            const path = file.path.startsWith('/') ? file.path : '/' + file.path;
            files[path] = file.content || "";
        });

        // Add tsconfig for path aliases
        files["/tsconfig.json"] = JSON.stringify({
        compilerOptions: {
            baseUrl: ".",
            paths: {
            "@/*": ["./src/*"]
            },
            jsx: "react-jsx",
            target: "esnext",
            module: "esnext",
            moduleResolution: "node"
        }
        }, null, 2);

        // Create entry point App.tsx that renders src/app/page.tsx
        // Find the main page file (look for src/app/page.tsx, or any page.tsx)
        const pageFilePath = Object.keys(files).find(path => path.endsWith("/page.tsx") || path.endsWith("/index.tsx"));

        if (pageFilePath) {
            // Adjust import path relative to root
            // FIX: If path is /src/app/page.tsx, import should be ./src/app/page
            // Sandpack file structure is flat at root, so absolute paths work best if mapped correctly.
            // But we configured tsconfig paths @/* -> ./src/*
            
            // Let's use the alias for cleaner imports if possible, or relative path
            const importPath = pageFilePath.startsWith("/src/") 
                ? "@" + pageFilePath.substring(4).replace(/\.tsx$/, "") 
                : "." + pageFilePath.replace(/\.tsx$/, "");
            
            files["/App.tsx"] = `
import React from "react";
import Page from "${importPath}";
import "./src/app/globals.css";

export default function App() {
  return <Page />;
}
`;
        } else {
            // Fallback if no page.tsx
            files["/App.tsx"] = `export default function App() { return <div style={{padding: 20, color: 'white'}}>No page.tsx found in generated files. Check the Code tab to see what was generated.</div> }`;
        }

        // VITE TEMPLATE FIX: Point index.html to App.tsx
        files["/index.html"] = `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Preview</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/index.tsx"></script>
  </body>
</html>`;

        // REMOVE CONFIG FILES to prevent build errors in Sandpack
        delete files["/postcss.config.js"];
        delete files["/tailwind.config.ts"];
        delete files["/next.config.mjs"];
        // Also remove vite.config.js if AI generated it, as Sandpack handles its own config
        delete files["/vite.config.ts"];
        delete files["/vite.config.js"];

        // NEXT.JS SHIMS (CRITICAL FOR 99% SUCCESS)
        // Since we are running in Vite (Sandpack), Next.js specific modules like next/link, next/image, next/navigation
        // will crash the app. We must shim them.
        
        files["/node_modules/next/link.js"] = `
            import React from 'react';
            export default function Link({ children, href, ...props }) {
                return React.createElement('a', { href, ...props }, children);
            }
        `;

        files["/node_modules/next/image.js"] = `
            import React from 'react';
            export default function Image({ src, alt, width, height, ...props }) {
                return React.createElement('img', { src, alt, width, height, ...props });
            }
        `;
        
        files["/node_modules/next/navigation.js"] = `
            export function useRouter() {
                return { 
                    push: (url) => window.location.href = url,
                    replace: (url) => window.location.href = url,
                    back: () => window.history.back(),
                    forward: () => window.history.forward(),
                    refresh: () => window.location.reload(),
                };
            }
            export function usePathname() { return window.location.pathname; }
            export function useSearchParams() { return new URLSearchParams(window.location.search); }
            export function useParams() { return {}; }
        `;

        // Vite expects index.tsx as entry usually, or we can configure it.
        files["/index.tsx"] = `
import React, { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import "./src/app/globals.css";
import App from "./App";

const root = createRoot(document.getElementById("root"));
root.render(
  <StrictMode>
    <App />
  </StrictMode>
);
`;

        // Add basic global css if missing
        if (!files["/src/app/globals.css"]) {
            files["/src/app/globals.css"] = `
@tailwind base;
@tailwind components;
@tailwind utilities;

html, body {
  height: 100%;
  margin: 0;
  padding: 0;
  width: 100%;
}

body {
  font-family: sans-serif;
  background-color: #ffffff;
  color: #000000;
}
`;
        }

        // SANITIZE GLOBALS.CSS for Preview
        if (files["/src/app/globals.css"]) {
            const content = files["/src/app/globals.css"];
            
            // Extract :root block safely
            let rootBlock = "";
            try {
                const rootMatch = content.match(/:root\s*\{[^}]+\}/);
                rootBlock = rootMatch ? rootMatch[0] : "";
            } catch (e) { console.warn("CSS Parse Error", e); }
            
            // Extract .dark block if exists
            let darkBlock = "";
            try {
                const darkMatch = content.match(/\.dark\s*\{[^}]+\}/);
                darkBlock = darkMatch ? darkMatch[0] : "";
            } catch (e) { console.warn("CSS Parse Error", e); }

            // Create a SAFE version for preview
            files["/src/app/globals.css"] = `
/* Safe Preview CSS - Generated by PreviewPanel */
@layer base {
  ${rootBlock}
  ${darkBlock}
}

body {
  background-color: hsl(var(--background));
  color: hsl(var(--foreground));
  font-feature-settings: "rlig" 1, "calt" 1;
}

* {
  border-color: hsl(var(--border));
}

/* Scrollbar */
::-webkit-scrollbar {
    width: 8px;
}
::-webkit-scrollbar-track {
    background: transparent;
}
::-webkit-scrollbar-thumb {
    background: hsl(var(--muted));
    border-radius: 4px;
}
`;
        }

        return files;
    } catch (error) {
        console.error("Error generating preview files:", error);
        toast.error("Preview generation failed. Please check the code.");
        return {};
    }
  }, [generatedFiles, hasFiles]);

  return (
    <div className="h-full flex flex-col">
        {/* Address Bar */}
        <div className="h-10 border-b bg-muted/10 flex items-center px-4 gap-4">
            <div className="flex items-center gap-1.5">
                <div className="w-2.5 h-2.5 rounded-full bg-red-500/80" />
                <div className="w-2.5 h-2.5 rounded-full bg-yellow-500/80" />
                <div className="w-2.5 h-2.5 rounded-full bg-green-500/80" />
            </div>
            
            <div className="flex-1 flex items-center bg-background border rounded-md h-7 px-3 text-xs text-muted-foreground">
                <div className="flex-1 truncate">
                    {viewMode === "preview" ? ((previewUrl === "sandpack" || (!previewUrl && hasFiles)) ? "Local Simulation" : previewUrl || "http://localhost:3000") : (selectedFile ? `view-source://${selectedFile}` : "Ready")}
                </div>
                {viewMode === "preview" && (previewUrl || hasFiles) && (
                    <Button 
                        variant="ghost" 
                        size="icon" 
                        className="h-5 w-5 ml-2 hover:bg-transparent"
                        onClick={handleRefresh}
                        title="Force Refresh Preview"
                    >
                        <RefreshCw className="w-3 h-3" />
                    </Button>
                )}
            </div>

            <div className="flex bg-muted rounded-lg p-0.5">
                <button
                    onClick={() => setViewMode("preview")}
                    disabled={!canPreview}
                    className={cn(
                        "px-2 py-0.5 text-xs rounded-md transition-all",
                        viewMode === "preview" ? "bg-background shadow-sm text-foreground" : "text-muted-foreground hover:text-foreground",
                        !canPreview && "opacity-50 cursor-not-allowed"
                    )}
                >
                    Preview
                </button>
                <button
                    onClick={() => setViewMode("code")}
                    className={cn(
                        "px-2 py-0.5 text-xs rounded-md transition-all",
                        viewMode === "code" ? "bg-background shadow-sm text-foreground" : "text-muted-foreground hover:text-foreground"
                    )}
                >
                    Code
                </button>
            </div>

            <div className="flex items-center gap-1 ml-2 border-l pl-2">
                 <Button 
                    variant="ghost" 
                    size="icon" 
                    className="h-8 w-8 text-muted-foreground hover:text-foreground"
                    onClick={handleDownload}
                    title="Download Source Code"
                 >
                    <Download className="w-4 h-4" />
                </Button>
                <Button 
                    variant="ghost" 
                    size="icon" 
                    className={cn("h-8 w-8 text-muted-foreground hover:text-indigo-400", isDeploying && "text-indigo-500 animate-pulse")}
                    onClick={handleDeploy}
                    title="Deploy to Production"
                >
                    <Rocket className="w-4 h-4" />
                </Button>
                <Button 
                    variant="ghost" 
                    size="icon" 
                    className="h-8 w-8 text-muted-foreground hover:text-foreground"
                    onClick={handleExternalLink}
                    title="Open in New Tab"
                >
                    <ExternalLink className="w-4 h-4" />
                </Button>
            </div>
        </div>

        {/* Content Area */}
        <div className="flex-1 relative bg-neutral-950 overflow-hidden">
            {viewMode === "preview" && canPreview ? (
                (previewUrl === "sandpack" || (!previewUrl && hasFiles)) ? (
                    <SandpackProvider 
                        key={key}
                        template="vite-react-ts"
                        theme="dark"
                        files={sandpackFiles}
                        style={{ height: "100%", width: "100%" }}
                        customSetup={{
                            dependencies: {
                                "framer-motion": "^11.0.0",
                                "lucide-react": "^0.300.0",
                                "clsx": "^2.1.0",
                                "tailwind-merge": "^2.2.0",
                                "class-variance-authority": "^0.7.0",
                                "mini-svg-data-uri": "^1.4.4",
                                "tailwindcss-animate": "^1.0.7",
                                "@radix-ui/react-slot": "^1.0.2",
                                "@radix-ui/react-label": "^2.0.2",
                                "@radix-ui/react-avatar": "^1.0.4",
                                "@radix-ui/react-dialog": "^1.0.5",
                                "@radix-ui/react-dropdown-menu": "^2.0.6",
                                "@radix-ui/react-separator": "^1.0.3",
                                "@radix-ui/react-switch": "^1.0.3",
                                "@radix-ui/react-scroll-area": "^1.0.5",
                                "@radix-ui/react-accordion": "^1.0.1",
                                "@radix-ui/react-tabs": "^1.0.4",
                                "@radix-ui/react-popover": "^1.0.7",
                                "recharts": "^2.12.0",
                                "date-fns": "^3.3.1"
                            },
                            externalResources: [
                                "https://cdn.tailwindcss.com",
                                "https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap"
                            ]
                        }}
                        options={{
                            activeFile: "/App.tsx",
                            initMode: "lazy", // Changed from user-visible to lazy to avoid timeout on weak connections
                            initModeObserverOptions: { rootMargin: '1000px 0px' },
                            bundlerURL: "https://sandpack-bundler.codesandbox.io", // Explicitly use official bundler
                        }}
                    >
                        <SandpackLayout style={{ height: "100%", width: "100%", borderRadius: 0, border: "none" }}>
                            <SandpackPreview 
                                style={{ height: "100%", width: "100%" }} 
                                showNavigator={false} 
                                showOpenInCodeSandbox={false} 
                                showRefreshButton={false}
                                showRestartButton={false}
                                actionsChildren={
                                    <button 
                                        onClick={handleRefresh}
                                        className="p-2 text-white/50 hover:text-white transition-colors"
                                        title="Reload Preview"
                                    >
                                        <RefreshCw className="w-4 h-4" />
                                    </button>
                                }
                            />
                        </SandpackLayout>
                    </SandpackProvider>
                ) : (
                    <iframe
                        key={key}
                        src={previewUrl || undefined}
                        className="w-full h-full border-0"
                        title="Live Preview"
                    />
                )
            ) : viewMode === "code" ? (
                <div className="flex h-full">
                    <div className="w-48 border-r bg-muted/10 flex flex-col">
                        <div className="p-2 text-xs font-semibold text-muted-foreground uppercase tracking-wider">
                            Files
                        </div>
                        <ScrollArea className="flex-1">
                            <div className="space-y-0.5 p-2">
                                {generatedFiles.map((file: any) => (
                                    <button
                                        key={file.path}
                                        onClick={() => setSelectedFile(file.path)}
                                        className={cn(
                                            "w-full text-left px-2 py-1.5 text-xs rounded-md flex items-center gap-2 transition-colors",
                                            selectedFile === file.path ? "bg-primary/10 text-primary" : "text-muted-foreground hover:bg-muted/50"
                                        )}
                                    >
                                        <FileCode className="w-3.5 h-3.5" />
                                        <span className="truncate">{file.path.split('/').pop()}</span>
                                    </button>
                                ))}
                            </div>
                        </ScrollArea>
                    </div>
                    <div className="flex-1 flex flex-col min-w-0">
                        <ScrollArea className="flex-1">
                             <pre className="p-4 text-sm font-mono tab-4">
                                <code>{selectedFileContent}</code>
                            </pre>
                        </ScrollArea>
                    </div>
                </div>
            ) : (
                <div className="flex flex-col items-center justify-center h-full text-muted-foreground gap-4">
                    <div className="w-16 h-16 rounded-full bg-muted/50 flex items-center justify-center">
                        <Code2 className="w-8 h-8 opacity-50" />
                    </div>
                    <p>No preview available. Generate code to see it here.</p>
                </div>
            )}
        </div>
    </div>
  );
}
