"use client";

import React, { useState, useEffect } from "react";
import { useProjectStore } from "@/store/project-store";
import { RefreshCw, ExternalLink, FileCode, Code2, Download, Rocket, Share2, Loader2, Sparkles, AlertTriangle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { ScrollArea } from "@/components/ui/scroll-area";
import { cn } from "@/lib/utils";
import { SandpackProvider, SandpackLayout, SandpackPreview } from "@codesandbox/sandpack-react";
import JSZip from "jszip";
import { saveAs } from "file-saver";
import { toast } from "sonner";

export function PreviewPanel() {
  const { previewUrl, generatedFiles, projectName, setGeneratedFiles } = useProjectStore();
  const [key, setKey] = useState(0);
  const [selectedFile, setSelectedFile] = useState<string | null>(null);
  const [viewMode, setViewMode] = useState<"preview" | "code">("code");
  const [isDeploying, setIsDeploying] = useState(false);
  const [isFixing, setIsFixing] = useState(false);

  const handleRefresh = () => {
    setKey(prev => prev + 1);
  };

  const handleDownload = async () => {
    if (!generatedFiles || generatedFiles.length === 0) {
        toast.error("No files to download.");
        return;
    }

    try {
        const zip = new JSZip();
        
        // Add all generated files to the zip
        generatedFiles.forEach((file: any) => {
            // Remove leading slash if present
            const path = file.path.startsWith('/') ? file.path.substring(1) : file.path;
            zip.file(path, file.content);
        });

        // Add a basic README
        zip.file("README.md", `# ${projectName || "Project"}\n\nGenerated by Superior AI.\n\n## Getting Started\n\n1. Run \`npm install\`\n2. Run \`npm run dev\`\n`);

        const content = await zip.generateAsync({ type: "blob" });
        saveAs(content, `${projectName?.replace(/\s+/g, '-').toLowerCase() || "project"}.zip`);
        toast.success("Project downloaded successfully!");
    } catch (error) {
        console.error("Download failed:", error);
        toast.error("Failed to create zip file.");
    }
  };

  const handleDeploy = async () => {
    setIsDeploying(true);
    
    // "Real" Deployment Flow for a Client-Side App:
    // 1. Download the code (so user has it)
    // 2. Open Vercel Import page (so user can deploy it)
    
    toast.info("Preparing for deployment...");
    
    try {
        await handleDownload(); // Auto-download first
        
        setTimeout(() => {
            setIsDeploying(false);
            toast("🚀 Ready to Deploy!", {
                description: "Source code downloaded. Upload to Vercel to go live.",
                action: {
                    label: "Open Vercel",
                    onClick: () => window.open("https://vercel.com/new", "_blank"),
                },
                duration: 10000,
            });
        }, 1500);
    } catch (e) {
        setIsDeploying(false);
        toast.error("Deployment preparation failed.");
    }
  };

  const handleExternalLink = () => {
     if (previewUrl && previewUrl !== "sandpack") {
         window.open(previewUrl, "_blank");
     } else {
        toast.info("Click the 'Open in CodeSandbox' icon inside the preview to edit externally.");
     }
  };

  // --- SELF-CORRECTION LOOP: AUTO-FIX HANDLER ---
  const handleAutoFix = async (errorMessage: string) => {
    if (isFixing) return;
    setIsFixing(true);
    toast.loading("Superior Self-Healing: Fixing Runtime Error...", { id: "fix-loader" });

    try {
        // Find the most likely culprit file (usually page.tsx or the one causing error if we knew)
        // For now, we send the main page and components.
        const pageFile = generatedFiles.find((f: any) => f.path.includes("page.tsx"));
        
        const res = await fetch("/api/ai/fix", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({
                errorMessage,
                file: pageFile?.path || "src/app/page.tsx",
                code: pageFile?.content || "",
                allFiles: generatedFiles
            })
        });

        const data = await res.json();
        
        if (data.fixedCode && pageFile) {
            // Update the file in the store
            const newFiles = generatedFiles.map((f: any) => 
                f.path === pageFile.path ? { ...f, content: data.fixedCode } : f
            );
            setGeneratedFiles(newFiles);
            toast.success("Code Auto-Corrected Successfully!", { id: "fix-loader" });
            handleRefresh(); // Reload preview
        } else {
            toast.error("Could not auto-fix this error.", { id: "fix-loader" });
        }

    } catch (e) {
        console.error("Auto-fix failed:", e);
        toast.error("Self-Healing System failed.", { id: "fix-loader" });
    } finally {
        setIsFixing(false);
    }
  };

  // --- LISTENER FOR SANDBOX ERRORS ---
  useEffect(() => {
    const handleMessage = (event: MessageEvent) => {
        if (event.data?.type === "SANDBOX_RUNTIME_ERROR") {
            console.log("Superior Error Detector Caught:", event.data.message);
            // Trigger Auto-Fix
            handleAutoFix(event.data.message);
        }
    };

    window.addEventListener("message", handleMessage);
    return () => window.removeEventListener("message", handleMessage);
  }, [generatedFiles, isFixing]); // Re-bind if files change to ensure freshness

  const hasFiles = generatedFiles && Array.isArray(generatedFiles) && generatedFiles.length > 0;
  
  // Select first file by default if none selected
  React.useEffect(() => {
    if (hasFiles && !selectedFile) {
        const pageFile = generatedFiles.find((f: any) => f?.path?.includes("page.tsx")) || generatedFiles[0];
        if (pageFile && pageFile.path) {
            setSelectedFile(pageFile.path);
        }
    }
    // Auto-switch to preview if previewUrl is set (even if "sandpack"), otherwise default to code
    if (!previewUrl && hasFiles && viewMode === "preview") {
        // Allow staying in preview if we have files (Sandpack mode)
    } else if (!previewUrl && hasFiles && viewMode !== "preview") {
         // Don't auto-switch to code if we have files, let user choose
    }
  }, [hasFiles, selectedFile, generatedFiles, previewUrl, viewMode]);

  const selectedFileContent = generatedFiles?.find((f: any) => f?.path === selectedFile)?.content || "";
  const canPreview = !!(previewUrl || hasFiles);

  // Prepare files for Sandpack
  const sandpackFiles = React.useMemo(() => {
    if (!hasFiles) return {};
    
    try {
        const files: Record<string, string> = {};
        
        // Add all generated files
        generatedFiles.forEach((file: any) => {
            if (!file || !file.path) return;
            if (file.path.endsWith("package.json")) return;

            // Ensure path starts with /
            const path = file.path.startsWith('/') ? file.path : '/' + file.path;
            files[path] = file.content || "";
        });

        // Add tsconfig for path aliases
        files["/tsconfig.json"] = JSON.stringify({
        compilerOptions: {
            baseUrl: ".",
            paths: { "@/*": ["./src/*"] },
            jsx: "react-jsx",
            target: "esnext",
            module: "esnext",
            moduleResolution: "node"
        }
        }, null, 2);

        // --- INJECT ERROR BOUNDARY COMPONENT ---
        files["/src/components/ErrorBoundary.tsx"] = `
import React, { Component, ErrorInfo, ReactNode } from "react";

interface Props { children: ReactNode }
interface State { hasError: boolean; error: Error | null }

export class ErrorBoundary extends Component<Props, State> {
  constructor(props: Props) {
    super(props);
    this.state = { hasError: false, error: null };
  }

  static getDerivedStateFromError(error: Error): State {
    return { hasError: true, error };
  }

  componentDidCatch(error: Error, errorInfo: ErrorInfo) {
    // Send error to parent (Superior Platform)
    window.parent.postMessage({
      type: "SANDBOX_RUNTIME_ERROR",
      message: error.message,
      stack: error.stack
    }, "*");
  }

  render() {
    if (this.state.hasError) {
      return (
        <div className="flex flex-col items-center justify-center min-h-screen bg-neutral-950 text-red-400 p-6 text-center">
          <div className="bg-red-950/30 border border-red-500/30 p-6 rounded-xl max-w-md w-full">
             <h2 className="text-xl font-bold mb-2 text-red-500">Runtime Error Detected</h2>
             <p className="text-sm text-neutral-400 mb-4">Superior Self-Healing Protocol Activated</p>
             <div className="bg-black/50 p-3 rounded text-xs font-mono text-left overflow-auto max-h-40 mb-4">
               {this.state.error?.message}
             </div>
             <div className="flex items-center justify-center gap-2 text-sm text-green-400 animate-pulse">
               <span className="w-2 h-2 rounded-full bg-green-500"/>
               AI is analyzing and fixing...
             </div>
          </div>
        </div>
      );
    }
    return this.props.children;
  }
}
`;

        // Create entry point App.tsx
        const pageFilePath = Object.keys(files).find(path => path.endsWith("/page.tsx") || path.endsWith("/index.tsx"));

        if (pageFilePath) {
            const importPath = pageFilePath.startsWith("/src/") 
                ? "@" + pageFilePath.substring(4).replace(/\.tsx$/, "") 
                : "." + pageFilePath.replace(/\.tsx$/, "");
            
            files["/App.tsx"] = `
import React from "react";
import Page from "${importPath}";
import "./src/app/globals.css"; 

export default function App() {
  return (
    <div className="min-h-screen bg-background font-body antialiased text-foreground selection:bg-indigo-100">
       <Page />
    </div>
  );
}
`;
        } else {
            files["/App.tsx"] = `export default function App() { return <div>No page.tsx found.</div> }`;
        }
        
        // --- NEXT.JS SHIMS ---
        Object.keys(files).forEach(path => {
            let content = files[path];
            if (content.includes('from "next/link"') || content.includes("from 'next/link'")) {
                 content = content.replace(/import\s+Link\s+from\s+['"]next\/link['"];?/g, `const Link = ({ href, children, ...props }: any) => <a href={href} {...props}>{children}</a>;`);
            }
            if (content.includes('from "next/image"') || content.includes("from 'next/image'")) {
                 content = content.replace(/import\s+Image\s+from\s+['"]next\/image['"];?/g, `const Image = ({ src, alt, ...props }: any) => <img src={src} alt={alt} {...props} />;`);
            }
            if (content.includes('from "next/navigation"') || content.includes("from 'next/navigation'")) {
                 content = content.replace(/import\s+\{\s*useRouter\s*\}\s+from\s+['"]next\/navigation['"];?/g, `const useRouter = () => ({ push: () => {}, replace: () => {}, back: () => {} });`);
            }
            files[path] = content;
        });
        
        // VITE TEMPLATE FIX
        const indexHtmlContent = `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Preview</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&family=Outfit:wght@500;700&display=swap" rel="stylesheet">
    <script src="https://cdn.tailwindcss.com"></script>
    <script>
      tailwind.config = {
        darkMode: 'class',
        theme: {
          container: { center: true, padding: "2rem", screens: { "2xl": "1400px" } },
          extend: {
            fontFamily: { heading: ['Outfit', 'sans-serif'], body: ['Inter', 'sans-serif'] },
            colors: {
              border: "hsl(var(--border))", input: "hsl(var(--input))", ring: "hsl(var(--ring))", background: "hsl(var(--background))", foreground: "hsl(var(--foreground))",
              primary: { DEFAULT: "hsl(var(--primary))", foreground: "hsl(var(--primary-foreground))" },
              secondary: { DEFAULT: "hsl(var(--secondary))", foreground: "hsl(var(--secondary-foreground))" },
              destructive: { DEFAULT: "hsl(var(--destructive))", foreground: "hsl(var(--destructive-foreground))" },
              muted: { DEFAULT: "hsl(var(--muted))", foreground: "hsl(var(--muted-foreground))" },
              accent: { DEFAULT: "hsl(var(--accent))", foreground: "hsl(var(--accent-foreground))" },
              popover: { DEFAULT: "hsl(var(--popover))", foreground: "hsl(var(--popover-foreground))" },
              card: { DEFAULT: "hsl(var(--card))", foreground: "hsl(var(--card-foreground))" },
            },
            borderRadius: { lg: "var(--radius)", md: "calc(var(--radius) - 2px)", sm: "calc(var(--radius) - 4px)" },
            keyframes: { "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } }, "accordion-up": { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } } },
            animation: { "accordion-down": "accordion-down 0.2s ease-out", "accordion-up": "accordion-up 0.2s ease-out" },
          }
        }
      }
    </script>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/index.tsx"></script>
  </body>
</html>`;
        
        files["/index.html"] = indexHtmlContent;
        files["/public/index.html"] = indexHtmlContent;

        delete files["/postcss.config.js"];
        delete files["/tailwind.config.ts"];
        delete files["/next.config.mjs"];
        
        files["/vite.config.ts"] = `
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
export default defineConfig({
  plugins: [react()],
  resolve: { alias: { '@': '/src' } },
})
`;

        files["/node_modules/next/link.js"] = `import React from 'react'; export default function Link({ children, href, ...props }) { return React.createElement('a', { href, ...props }, children); }`;
        files["/node_modules/next/image.js"] = `import React from 'react'; export default function Image({ src, alt, width, height, ...props }) { return React.createElement('img', { src, alt, width, height, ...props }); }`;
        files["/node_modules/next/navigation.js"] = `export function useRouter() { return { push: () => {}, replace: () => {}, back: () => {}, refresh: () => {} }; } export function usePathname() { return window.location.pathname; } export function useSearchParams() { return new URLSearchParams(window.location.search); } export function useParams() { return {}; }`;

        // --- UPDATE INDEX.TSX TO USE ERROR BOUNDARY ---
        files["/index.tsx"] = `
import React, { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import "./src/app/globals.css";
import App from "./App";
import { ErrorBoundary } from "./src/components/ErrorBoundary";

const root = createRoot(document.getElementById("root"));
root.render(
  <StrictMode>
    <ErrorBoundary>
      <App />
    </ErrorBoundary>
  </StrictMode>
);
`;

        if (!files["/src/app/globals.css"]) {
            files["/src/app/globals.css"] = `@tailwind base; @tailwind components; @tailwind utilities; body { background: #fff; color: #000; }`;
        }
        
        // Sanitize CSS
        if (files["/src/app/globals.css"]) {
            const content = files["/src/app/globals.css"];
            let rootBlock = "", darkBlock = "";
            try { rootBlock = content.match(/:root\s*\{[^}]+\}/)?.[0] || ""; } catch {}
            try { darkBlock = content.match(/\.dark\s*\{[^}]+\}/)?.[0] || ""; } catch {}
            files["/src/app/globals.css"] = `/* Safe Preview CSS */ @layer base { ${rootBlock} ${darkBlock} } body { background-color: hsl(var(--background)); color: hsl(var(--foreground)); } * { border-color: hsl(var(--border)); }`;
        }

        return files;
    } catch (error) {
        console.error("Error generating preview files:", error);
        return {};
    }
  }, [generatedFiles, hasFiles]);

  return (
    <div className="h-full flex flex-col">
        {/* Address Bar */}
        <div className="h-10 border-b bg-muted/10 flex items-center px-4 gap-4">
            <div className="flex items-center gap-1.5">
                <div className="w-2.5 h-2.5 rounded-full bg-red-500/80" />
                <div className="w-2.5 h-2.5 rounded-full bg-yellow-500/80" />
                <div className="w-2.5 h-2.5 rounded-full bg-green-500/80" />
            </div>
            
            <div className="flex-1 flex items-center bg-background border rounded-md h-7 px-3 text-xs text-muted-foreground">
                <div className="flex-1 truncate flex items-center gap-2">
                    {isFixing ? (
                         <span className="text-amber-500 flex items-center gap-1 font-semibold animate-pulse">
                            <Sparkles className="w-3 h-3" /> SELF-HEALING IN PROGRESS...
                         </span>
                    ) : (
                        viewMode === "preview" ? ((previewUrl === "sandpack" || (!previewUrl && hasFiles)) ? "Local Simulation" : previewUrl || "http://localhost:3000") : (selectedFile ? `view-source://${selectedFile}` : "Ready")
                    )}
                </div>
                {viewMode === "preview" && (previewUrl || hasFiles) && (
                    <Button variant="ghost" size="icon" className="h-5 w-5 ml-2 hover:bg-transparent" onClick={handleRefresh} title="Force Refresh">
                        <RefreshCw className={cn("w-3 h-3", isFixing && "animate-spin")} />
                    </Button>
                )}
            </div>

            <div className="flex bg-muted rounded-lg p-0.5">
                <button onClick={() => setViewMode("preview")} disabled={!canPreview} className={cn("px-2 py-0.5 text-xs rounded-md transition-all", viewMode === "preview" ? "bg-background shadow-sm text-foreground" : "text-muted-foreground hover:text-foreground", !canPreview && "opacity-50 cursor-not-allowed")}>Preview</button>
                <button onClick={() => setViewMode("code")} className={cn("px-2 py-0.5 text-xs rounded-md transition-all", viewMode === "code" ? "bg-background shadow-sm text-foreground" : "text-muted-foreground hover:text-foreground")}>Code</button>
            </div>

            <div className="flex items-center gap-1 ml-2 border-l pl-2">
                 <Button variant="ghost" size="icon" className="h-8 w-8 text-muted-foreground hover:text-foreground" onClick={handleDownload} title="Download Source Code">
                    <Download className="w-4 h-4" />
                </Button>
                <Button variant="ghost" size="icon" className={cn("h-8 w-8 text-muted-foreground hover:text-indigo-400", isDeploying && "text-indigo-500 animate-pulse")} onClick={handleDeploy} title="Deploy to Production">
                    <Rocket className="w-4 h-4" />
                </Button>
                <Button variant="ghost" size="icon" className="h-8 w-8 text-muted-foreground hover:text-foreground" onClick={handleExternalLink} title="Open in New Tab">
                    <ExternalLink className="w-4 h-4" />
                </Button>
            </div>
        </div>

        {/* Content Area */}
        <div className="flex-1 relative bg-neutral-950 overflow-hidden">
            {viewMode === "preview" && canPreview ? (
                (previewUrl === "sandpack" || (!previewUrl && hasFiles)) ? (
                    <div className="w-full h-full relative">
                        {isFixing && (
                            <div className="absolute inset-0 z-50 bg-black/60 backdrop-blur-sm flex flex-col items-center justify-center text-white">
                                <Loader2 className="w-10 h-10 animate-spin text-green-500 mb-4" />
                                <h3 className="text-xl font-bold text-green-400">Superior Self-Healing Active</h3>
                                <p className="text-neutral-400 text-sm mt-2">Correcting runtime errors automatically...</p>
                            </div>
                        )}
                        <SandpackProvider 
                            key={key}
                            template="vite-react-ts"
                            theme="dark"
                            files={sandpackFiles}
                            style={{ height: "100%", width: "100%" }}
                            options={{
                                activeFile: "/App.tsx",
                                initMode: "user-visible",
                                initModeObserverOptions: { rootMargin: '1000px 0px' },
                                externalResources: ["https://cdn.tailwindcss.com", "https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&family=Outfit:wght@500;700&display=swap"]
                            }}
                            customSetup={{
                                dependencies: {
                                    "framer-motion": "^11.0.0", 
                                    "lucide-react": "^0.300.0", 
                                    "clsx": "^2.1.0", 
                                    "tailwind-merge": "^2.2.0", 
                                    "class-variance-authority": "^0.7.0", 
                                    "mini-svg-data-uri": "^1.4.4", 
                                    "tailwindcss-animate": "^1.0.7",
                                    "@radix-ui/react-slot": "^1.0.2", 
                                    "@radix-ui/react-label": "^2.0.2", 
                                    "@radix-ui/react-avatar": "^1.0.4", 
                                    "@radix-ui/react-dialog": "^1.0.5", 
                                    "@radix-ui/react-dropdown-menu": "^2.0.6", 
                                    "@radix-ui/react-separator": "^1.0.3", 
                                    "@radix-ui/react-switch": "^1.0.3", 
                                    "@radix-ui/react-scroll-area": "^1.0.5", 
                                    "@radix-ui/react-accordion": "^1.0.1", 
                                    "@radix-ui/react-tabs": "^1.0.4", 
                                    "@radix-ui/react-popover": "^1.0.7",
                                    "recharts": "^2.12.0", 
                                    "date-fns": "^3.3.1",
                                    "react-router-dom": "^6.22.0" // Add router for navigation simulation
                                },
                            }}
                        >
                            <SandpackLayout style={{ height: "100%", width: "100%", borderRadius: 0, border: "none" }}>
                                <SandpackPreview 
                                    style={{ height: "100%", width: "100%" }} 
                                    showNavigator={false} showOpenInCodeSandbox={false} showRefreshButton={false} showRestartButton={false}
                                    actionsChildren={
                                        <button onClick={handleRefresh} className="p-2 text-white/50 hover:text-white transition-colors" title="Reload Preview">
                                            <RefreshCw className="w-4 h-4" />
                                        </button>
                                    }
                                />
                            </SandpackLayout>
                        </SandpackProvider>
                    </div>
                ) : (
                    <iframe key={key} src={previewUrl || undefined} className="w-full h-full border-0" title="Live Preview" />
                )
            ) : viewMode === "code" ? (
                <div className="flex h-full">
                    <div className="w-48 border-r bg-muted/10 flex flex-col">
                        <div className="p-2 text-xs font-semibold text-muted-foreground uppercase tracking-wider">Files</div>
                        <ScrollArea className="flex-1">
                            <div className="space-y-0.5 p-2">
                                {generatedFiles.map((file: any, idx: number) => {
                                    if (!file || !file.path) return null;
                                    return (
                                    <button key={file.path || idx} onClick={() => setSelectedFile(file.path)} className={cn("w-full text-left px-2 py-1.5 text-xs rounded-md flex items-center gap-2 transition-colors", selectedFile === file.path ? "bg-primary/10 text-primary" : "text-muted-foreground hover:bg-muted/50")}>
                                        <FileCode className="w-3.5 h-3.5" /> <span className="truncate">{file.path.split('/').pop()}</span>
                                    </button>
                                    );
                                })}
                            </div>
                        </ScrollArea>
                    </div>
                    <div className="flex-1 flex flex-col min-w-0">
                        <ScrollArea className="flex-1">
                             <pre className="p-4 text-sm font-mono tab-4"><code>{selectedFileContent}</code></pre>
                        </ScrollArea>
                    </div>
                </div>
            ) : (
                <div className="flex flex-col items-center justify-center h-full text-muted-foreground gap-4">
                    <div className="w-16 h-16 rounded-full bg-muted/50 flex items-center justify-center"><Code2 className="w-8 h-8 opacity-50" /></div>
                    <p>No preview available. Generate code to see it here.</p>
                </div>
            )}
        </div>
    </div>
  );
}
