import { NextResponse } from 'next/server';
import OpenAI from 'openai';

export const maxDuration = 60;

export async function POST(req: Request) {
  try {
    const { prompt, plan } = await req.json();

    if (!prompt || !plan) {
      return NextResponse.json({ error: "Missing prompt or plan" }, { status: 400 });
    }

    if (!process.env.OPENAI_API_KEY) {
         // Simulation Mode: Return a High-Quality Template
         await new Promise(r => setTimeout(r, 1000));
         return NextResponse.json({
             files: [
                 { 
                    path: "README.md", 
                    content: `# ${prompt}\n\nGenerated by Superior.\n\n## Getting Started\n\nRun \`npm run dev\`` 
                 },
                 {
                    path: "package.json",
                    content: JSON.stringify({
                      "name": "superior-app",
                      "version": "0.1.0",
                      "private": true,
                      "scripts": {
                        "dev": "next dev",
                        "build": "next build",
                        "start": "next start",
                        "lint": "next lint"
                      },
                      "dependencies": {
                        "react": "^18",
                        "react-dom": "^18",
                        "next": "14.1.0",
                        "lucide-react": "^0.344.0",
                        "clsx": "^2.1.0",
                        "tailwind-merge": "^2.2.1",
                        "tailwindcss-animate": "^1.0.7",
                        "class-variance-authority": "^0.7.0",
                        "@radix-ui/react-slot": "^1.0.2",
                        "framer-motion": "^11.0.8"
                      },
                      "devDependencies": {
                        "@types/node": "^20",
                        "@types/react": "^18",
                        "@types/react-dom": "^18",
                        "autoprefixer": "^10.0.1",
                        "postcss": "^8",
                        "tailwindcss": "^3.3.0",
                        "typescript": "^5"
                      }
                    }, null, 2)
                 },
                 {
                    path: "tsconfig.json",
                    content: JSON.stringify({
                      "compilerOptions": {
                        "lib": ["dom", "dom.iterable", "esnext"],
                        "allowJs": true,
                        "skipLibCheck": true,
                        "strict": true,
                        "noEmit": true,
                        "esModuleInterop": true,
                        "module": "esnext",
                        "moduleResolution": "bundler",
                        "resolveJsonModule": true,
                        "isolatedModules": true,
                        "jsx": "preserve",
                        "incremental": true,
                        "baseUrl": ".",
                        "plugins": [
                          {
                            "name": "next"
                          }
                        ],
                        "paths": {
                          "@/*": ["./src/*"]
                        }
                      },
                      "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
                      "exclude": ["node_modules"]
                    }, null, 2)
                 },
                 {
                    path: "next.config.mjs",
                    content: `/** @type {import('next').NextConfig} */
const nextConfig = {};

export default nextConfig;`
                 },
                 {
                    path: "src/app/layout.tsx",
                    content: `
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "${prompt} - Generated by Superior",
  description: "Next.js Application generated by Superior",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
`
                 },
                 {
                    path: "src/app/globals.css",
                    content: `@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {
  :root {
    --background: 0 0% 100%;
    --foreground: 222.2 84% 4.9%;

    --card: 0 0% 100%;
    --card-foreground: 222.2 84% 4.9%;

    --popover: 0 0% 100%;
    --popover-foreground: 222.2 84% 4.9%;

    --primary: 222.2 47.4% 11.2%;
    --primary-foreground: 210 40% 98%;

    --secondary: 210 40% 96.1%;
    --secondary-foreground: 222.2 47.4% 11.2%;

    --muted: 210 40% 96.1%;
    --muted-foreground: 215.4 16.3% 46.9%;

    --accent: 210 40% 96.1%;
    --accent-foreground: 222.2 47.4% 11.2%;

    --destructive: 0 84.2% 60.2%;
    --destructive-foreground: 210 40% 98%;

    --border: 214.3 31.8% 91.4%;
    --input: 214.3 31.8% 91.4%;
    --ring: 222.2 84% 4.9%;

    --radius: 0.5rem;
  }

  .dark {
    --background: 222.2 84% 4.9%;
    --foreground: 210 40% 98%;

    --card: 222.2 84% 4.9%;
    --card-foreground: 210 40% 98%;

    --popover: 222.2 84% 4.9%;
    --popover-foreground: 210 40% 98%;

    --primary: 210 40% 98%;
    --primary-foreground: 222.2 47.4% 11.2%;

    --secondary: 217.2 32.6% 17.5%;
    --secondary-foreground: 210 40% 98%;

    --muted: 217.2 32.6% 17.5%;
    --muted-foreground: 215 20.2% 65.1%;

    --accent: 217.2 32.6% 17.5%;
    --accent-foreground: 210 40% 98%;

    --destructive: 0 62.8% 30.6%;
    --destructive-foreground: 210 40% 98%;

    --border: 217.2 32.6% 17.5%;
    --input: 217.2 32.6% 17.5%;
    --ring: 212.7 26.8% 83.9%;
  }
}

@layer base {
  * {
    @apply border-border;
  }
  body {
    @apply bg-background text-foreground;
  }
}`
                 },
                 { 
                    path: "src/app/page.tsx", 
                    content: `
import { Button } from "../components/ui/button";
import { Card } from "../components/ui/card";
import { Rocket, Zap, Shield, Globe } from "lucide-react";

export default function Home() {
  return (
    <main className="min-h-screen bg-background text-foreground flex flex-col">
      {/* Hero Section */}
      <section className="flex-1 flex flex-col items-center justify-center text-center px-4 py-20 bg-gradient-to-b from-background to-secondary/20">
        <div className="mb-8 p-3 bg-primary/10 rounded-full text-primary animate-pulse">
            <Rocket className="w-8 h-8" />
        </div>
        <h1 className="text-5xl md:text-7xl font-bold tracking-tighter mb-6 bg-clip-text text-transparent bg-gradient-to-r from-foreground to-foreground/70">
          ${prompt || "Future Awaits"}
        </h1>
        <p className="text-xl text-muted-foreground max-w-[600px] mb-10">
          This application was instantaneously generated by Superior. 
          Ready for scale, optimized for performance.
        </p>
        <div className="flex gap-4">
          <Button size="lg" className="bg-primary text-primary-foreground hover:opacity-90">
            Get Started
          </Button>
          <Button size="lg" variant="outline">
            Learn More
          </Button>
        </div>
      </section>

      {/* Features Grid */}
      <section className="py-20 px-4 max-w-6xl mx-auto w-full">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            <Card className="p-6 border-border/50 bg-card/50 backdrop-blur">
                <Zap className="w-10 h-10 text-yellow-500 mb-4" />
                <h3 className="text-xl font-bold mb-2">Lightning Fast</h3>
                <p className="text-muted-foreground">Deployed in seconds with Vercel's edge network.</p>
            </Card>
            <Card className="p-6 border-border/50 bg-card/50 backdrop-blur">
                <Shield className="w-10 h-10 text-blue-500 mb-4" />
                <h3 className="text-xl font-bold mb-2">Secure by Default</h3>
                <p className="text-muted-foreground">Enterprise-grade security headers and best practices.</p>
            </Card>
            <Card className="p-6 border-border/50 bg-card/50 backdrop-blur">
                <Globe className="w-10 h-10 text-green-500 mb-4" />
                <h3 className="text-xl font-bold mb-2">Global Scale</h3>
                <p className="text-muted-foreground">Ready to serve millions of users worldwide.</p>
            </Card>
        </div>
      </section>
    </main>
  );
}
` 
                 },
                 {
                    path: "src/components/ui/button.tsx",
                    content: `
import * as React from "react"
import { Slot } from "@radix-ui/react-slot"
import { cva, type VariantProps } from "class-variance-authority"
import { cn } from "../../lib/utils"

const buttonVariants = cva(
  "inline-flex items-center justify-center whitespace-nowrap rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50",
  {
    variants: {
      variant: {
        default: "bg-primary text-primary-foreground hover:bg-primary/90",
        destructive: "bg-destructive text-destructive-foreground hover:bg-destructive/90",
        outline: "border border-input bg-background hover:bg-accent hover:text-accent-foreground",
        secondary: "bg-secondary text-secondary-foreground hover:bg-secondary/80",
        ghost: "hover:bg-accent hover:text-accent-foreground",
        link: "text-primary underline-offset-4 hover:underline",
      },
      size: {
        default: "h-10 px-4 py-2",
        sm: "h-9 rounded-md px-3",
        lg: "h-11 rounded-md px-8",
        icon: "h-10 w-10",
      },
    },
    defaultVariants: {
      variant: "default",
      size: "default",
    },
  }
)

export interface ButtonProps
  extends React.ButtonHTMLAttributes<HTMLButtonElement>,
    VariantProps<typeof buttonVariants> {
  asChild?: boolean
}

const Button = React.forwardRef<HTMLButtonElement, ButtonProps>(
  ({ className, variant, size, asChild = false, ...props }, ref) => {
    const Comp = asChild ? Slot : "button"
    return (
      <Comp
        className={cn(buttonVariants({ variant, size, className }))}
        ref={ref}
        {...props}
      />
    )
  }
)
Button.displayName = "Button"

export { Button, buttonVariants }
`
                 },
                 {
                    path: "src/components/ui/card.tsx",
                    content: `
import * as React from "react"
import { cn } from "../../lib/utils"

const Card = React.forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement>>(({ className, ...props }, ref) => (
  <div ref={ref} className={cn("rounded-lg border bg-card text-card-foreground shadow-sm", className)} {...props} />
))
Card.displayName = "Card"

export { Card }
`
                 },
                 {
                    path: "src/lib/utils.ts",
                    content: `
import { type ClassValue, clsx } from "clsx"
import { twMerge } from "tailwind-merge"

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}
`
                 },
                 {
                     path: "tailwind.config.ts",
                     content: `
import type { Config } from "tailwindcss"

const config = {
  darkMode: ["class"],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config

export default config
`
                 },
                 {
                     path: "postcss.config.js",
                     content: "module.exports = { plugins: { tailwindcss: {}, autoprefixer: {}, }, }"
                 },
                 {
                     path: "next-env.d.ts",
                     content: `/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file should not be edited
// see https://nextjs.org/docs/basic-features/typescript for more information.
`
                 }
             ]
         });
    }

    const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });
    const systemPrompt = `
    You are an Elite Senior Full-Stack Architect and UI/UX Designer.
    Your mission is to generate a PRODUCTION-READY, DEPLOYABLE Next.js 14 Application based on the User's Prompt and the Architect's Plan.

    The goal is to rival "Lovable.dev" or "v0.dev" in aesthetic quality, creating "Ultra-Premium" websites.

    DESIGN SYSTEM & PHILOSOPHY (STRICT):
    1.  **Layout & UX ("Bento Grid" & Luxury Spacing)**:
        -   NEVER use boring vertical stacking. Use **Bento Grids**, **Staggered Grids**, or **Asymmetric Layouts**.
        -   Use **Luxury Spacing**: Sections must have ample breathing room (e.g., \`py-24\` or \`py-32\`).
        -   Responsive: ALWAYS Mobile-First (\`grid-cols-1 md:grid-cols-3\`).

    2.  **Visual Polish (High-End Effects)**:
        -   **Glassmorphism**: Use backdrop blur for Navbars and Cards (e.g., \`backdrop-blur-md bg-white/10 border border-white/10\`).
        -   **Gradients**: Use sophisticated Mesh Gradients instead of flat colors (e.g., \`bg-gradient-to-br from-indigo-500 via-purple-500 to-pink-500\`).
        -   **Animations (Framer Motion)**:
            -   Elements MUST animate on scroll: \`initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ duration: 0.5 }}\`.
            -   Interactive Cards: \`whileHover={{ scale: 1.05 }}\`.
            -   Buttons: Use "magnetic" or "shimmer" effects.

    3.  **Typography & Content**:
        -   Use a **Serif** font for Headings (e.g., Playfair Display, Merino) and **Sans-serif** for Body (e.g., Inter, Geist) to create artistic contrast.
        -   **Copywriting**: Write professional, marketing-grade copy. Do not just list data; tell a story.

    4.  **High-End Components**:
        -   **Images**: Use Unsplash with keywords "high-end", "abstract", "minimalist". URL: \`https://images.unsplash.com/photo-[ID]?auto=format&fit=crop&w=800&q=80\`.
        -   **Icons**: Use \`lucide-react\` exclusively.
        -   **Theme**: Support **Dark/Light Mode** (using \`next-themes\`). Default to Dark Mode for that "premium" feel.

    CRITICAL RULES FOR DEPLOYMENT SUCCESS:
    1.  **NO ALIAS IMPORTS**: You MUST use relative imports (e.g., \`../components/ui/button\`) for everything. DO NOT use \`@/\`.
    2.  **SELF-CONTAINED**: If you import \`Button\`, you MUST generate \`src/components/ui/button.tsx\`.
    3.  **STRICT PATHS**: All files must be in \`src/\`.

    OUTPUT FORMAT:
    Return a JSON object with a single "files" array. Each item must have:
    - "path": The relative file path (e.g., "package.json", "src/app/page.tsx").
    - "content": The COMPLETE source code for that file.

    MANDATORY FILE STRUCTURE (You MUST generate ALL of these):
    
    1.  **Configuration Files**:
        -   \`package.json\`: Include: \`next\`, \`react\`, \`react-dom\`, \`lucide-react\`, \`framer-motion\`, \`clsx\`, \`tailwind-merge\`, \`tailwindcss-animate\`, \`next-themes\`.
        -   \`tsconfig.json\`: Standard Next.js config.
        -   \`next.config.js\`: Standard.
        -   \`tailwind.config.ts\`: Configure colors, fonts, and animations.
        -   \`postcss.config.js\`: Standard.
        -   \`src/app/globals.css\`: Define CSS variables for colors (background, foreground, etc.) and fonts.

    2.  **Core App Files**:
        -   \`src/app/layout.tsx\`: Wrap children in \`<ThemeProvider>\` (from \`next-themes\`). Include Fonts.
        -   \`src/app/providers.tsx\`: Create the ThemeProvider component.
        -   \`src/app/page.tsx\`: The "Ultra-Premium" Landing Page.
            -   **Hero**: Big, Bold, Animated.
            -   **Features**: Bento Grid layout.
            -   **Testimonials/Showcase**: Horizontal scroll or grid.
            -   **CTA**: Magnetic button.

    3.  **Components** (\`src/components/...\`):
        -   \`src/components/ui/button.tsx\`: High-end button with hover effects.
        -   \`src/components/ui/card.tsx\`: Glassmorphism card.
        -   \`src/components/theme-toggle.tsx\`: Button to switch themes.
        -   Feature components (Hero, Features, etc.).

    4.  **Database**:
        -   \`supabase/migrations/20240101_init.sql\`: Use the Plan's SQL.

    GENERATE A COMPLETE, WORKING REPOSITORY. DO NOT HALLUCINATE MISSING FILES.
    `;

    const userMessage = `
    Prompt: ${prompt}
    
    Plan SQL:
    ${plan.sql}
    
    Plan Description:
    ${plan.description}
    `;

    const completion = await openai.chat.completions.create({
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user", content: userMessage }
      ],
      model: "gpt-4o",
      response_format: { type: "json_object" },
    });

    const content = completion.choices[0].message.content;
    if (!content) throw new Error("No content from OpenAI");

    const result = JSON.parse(content);

    // 1. NORMALIZE FILE STRUCTURE: Ensure everything is in src/
    result.files = result.files.map((file: any) => {
      if (file.path.startsWith("app/") || file.path.startsWith("components/") || file.path.startsWith("lib/")) {
        file.path = "src/" + file.path;
      }
      return file;
    });

    // 3. ENFORCE CONFIGURATION FILES (PostCSS, Tailwind, Package.json, TSConfig)
    const MANDATORY_FILES = [
        {
             path: "postcss.config.js",
             content: "module.exports = { plugins: { tailwindcss: {}, autoprefixer: {}, }, }"
        },
        {
             path: "next.config.mjs",
             content: `/** @type {import('next').NextConfig} */
const nextConfig = {
  output: 'export',
  images: { unoptimized: true },
  eslint: {
    ignoreDuringBuilds: true,
  },
  typescript: {
    ignoreBuildErrors: true,
  },
};

export default nextConfig;`
        },
        {
             path: "tsconfig.json",
             content: JSON.stringify({
               "compilerOptions": {
                 "lib": ["dom", "dom.iterable", "esnext"],
                 "allowJs": true,
                 "skipLibCheck": true,
                 "strict": true,
                 "noEmit": true,
                 "esModuleInterop": true,
                 "module": "esnext",
                 "moduleResolution": "bundler",
                 "resolveJsonModule": true,
                 "isolatedModules": true,
                 "jsx": "preserve",
                 "incremental": true,
                 "plugins": [{ "name": "next" }],
                 "baseUrl": ".",
                 "paths": {
                   "@/*": ["./src/*"]
                 }
               },
               "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
               "exclude": ["node_modules"]
             }, null, 2)
        },
        {
             path: "tailwind.config.ts",
             content: `import type { Config } from "tailwindcss"

const config = {
  darkMode: ["class"],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config

export default config`
        },
        {
            path: "src/app/globals.css",
            content: `@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {
  :root {
    --background: 0 0% 100%;
    --foreground: 222.2 84% 4.9%;
    --card: 0 0% 100%;
    --card-foreground: 222.2 84% 4.9%;
    --popover: 0 0% 100%;
    --popover-foreground: 222.2 84% 4.9%;
    --primary: 222.2 47.4% 11.2%;
    --primary-foreground: 210 40% 98%;
    --secondary: 210 40% 96.1%;
    --secondary-foreground: 222.2 47.4% 11.2%;
    --muted: 210 40% 96.1%;
    --muted-foreground: 215.4 16.3% 46.9%;
    --accent: 210 40% 96.1%;
    --accent-foreground: 222.2 47.4% 11.2%;
    --destructive: 0 84.2% 60.2%;
    --destructive-foreground: 210 40% 98%;
    --border: 214.3 31.8% 91.4%;
    --input: 214.3 31.8% 91.4%;
    --ring: 222.2 84% 4.9%;
    --radius: 0.5rem;
  }

  .dark {
    --background: 222.2 84% 4.9%;
    --foreground: 210 40% 98%;
    --card: 222.2 84% 4.9%;
    --card-foreground: 210 40% 98%;
    --popover: 222.2 84% 4.9%;
    --popover-foreground: 210 40% 98%;
    --primary: 210 40% 98%;
    --primary-foreground: 222.2 47.4% 11.2%;
    --secondary: 217.2 32.6% 17.5%;
    --secondary-foreground: 210 40% 98%;
    --muted: 217.2 32.6% 17.5%;
    --muted-foreground: 215 20.2% 65.1%;
    --accent: 217.2 32.6% 17.5%;
    --accent-foreground: 210 40% 98%;
    --destructive: 0 62.8% 30.6%;
    --destructive-foreground: 210 40% 98%;
    --border: 217.2 32.6% 17.5%;
    --input: 217.2 32.6% 17.5%;
    --ring: 212.7 26.8% 83.9%;
  }
}

@layer base {
  * {
    @apply border-border;
  }
  body {
    @apply bg-background text-foreground;
  }
}`
        }
    ];

    // Merge Mandatory Files
    MANDATORY_FILES.forEach(mandatoryFile => {
        const existingIndex = result.files.findIndex((f: any) => f.path === mandatoryFile.path);
        if (existingIndex !== -1) {
            result.files[existingIndex] = mandatoryFile;
        } else {
            result.files.push(mandatoryFile);
        }
    });
    
    // 4. FORCE PACKAGE.JSON DEPENDENCIES & SCRIPTS
    const packageJsonIndex = result.files.findIndex((f: any) => f.path === "package.json");
    if (packageJsonIndex !== -1) {
        try {
            const pkg = JSON.parse(result.files[packageJsonIndex].content);
            pkg.scripts = {
                ...pkg.scripts,
                "dev": "next dev",
                "build": "next build",
                "start": "next start",
                "lint": "next lint"
            };
            pkg.dependencies = {
                ...pkg.dependencies,
                "lucide-react": "^0.344.0",
                "clsx": "^2.1.0",
                "tailwind-merge": "^2.2.1",
                "tailwindcss-animate": "^1.0.7",
                "class-variance-authority": "^0.7.0",
                "@radix-ui/react-slot": "^1.0.2",
                "framer-motion": "^11.0.8"
            };
            pkg.devDependencies = {
                ...pkg.devDependencies,
                "autoprefixer": "^10.0.1",
                "postcss": "^8",
                "tailwindcss": "^3.3.0"
            };
            result.files[packageJsonIndex].content = JSON.stringify(pkg, null, 2);
        } catch (e) {
            console.error("Failed to parse package.json", e);
        }
    }

    // 5. INJECT STANDARD COMPONENTS (If missing)
    const STANDARD_COMPONENTS = [
        {
            path: "src/lib/utils.ts",
            content: `import { type ClassValue, clsx } from "clsx"
import { twMerge } from "tailwind-merge"

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}`
        },
        {
            path: "src/components/ui/button.tsx",
            content: `import * as React from "react"
import { Slot } from "@radix-ui/react-slot"
import { cva, type VariantProps } from "class-variance-authority"
import { cn } from "../../lib/utils"

const buttonVariants = cva(
  "inline-flex items-center justify-center whitespace-nowrap rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50",
  {
    variants: {
      variant: {
        default: "bg-primary text-primary-foreground hover:bg-primary/90",
        destructive: "bg-destructive text-destructive-foreground hover:bg-destructive/90",
        outline: "border border-input bg-background hover:bg-accent hover:text-accent-foreground",
        secondary: "bg-secondary text-secondary-foreground hover:bg-secondary/80",
        ghost: "hover:bg-accent hover:text-accent-foreground",
        link: "text-primary underline-offset-4 hover:underline",
      },
      size: {
        default: "h-10 px-4 py-2",
        sm: "h-9 rounded-md px-3",
        lg: "h-11 rounded-md px-8",
        icon: "h-10 w-10",
      },
    },
    defaultVariants: {
      variant: "default",
      size: "default",
    },
  }
)

export interface ButtonProps
  extends React.ButtonHTMLAttributes<HTMLButtonElement>,
    VariantProps<typeof buttonVariants> {
  asChild?: boolean
}

const Button = React.forwardRef<HTMLButtonElement, ButtonProps>(
  ({ className, variant, size, asChild = false, ...props }, ref) => {
    const Comp = asChild ? Slot : "button"
    return (
      <Comp
        className={cn(buttonVariants({ variant, size, className }))}
        ref={ref}
        {...props}
      />
    )
  }
)
Button.displayName = "Button"

export { Button, buttonVariants }`
        },
        {
            path: "src/components/ui/card.tsx",
            content: `import * as React from "react"
import { cn } from "../../lib/utils"

const Card = React.forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement>>(({ className, ...props }, ref) => (
  <div ref={ref} className={cn("rounded-lg border bg-card text-card-foreground shadow-sm", className)} {...props} />
))
Card.displayName = "Card"

const CardHeader = React.forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement>>(({ className, ...props }, ref) => (
  <div ref={ref} className={cn("flex flex-col space-y-1.5 p-6", className)} {...props} />
))
CardHeader.displayName = "CardHeader"

const CardTitle = React.forwardRef<HTMLParagraphElement, React.HTMLAttributes<HTMLHeadingElement>>(({ className, ...props }, ref) => (
  <h3 ref={ref} className={cn("text-2xl font-semibold leading-none tracking-tight", className)} {...props} />
))
CardTitle.displayName = "CardTitle"

const CardDescription = React.forwardRef<HTMLParagraphElement, React.HTMLAttributes<HTMLParagraphElement>>(({ className, ...props }, ref) => (
  <p ref={ref} className={cn("text-sm text-muted-foreground", className)} {...props} />
))
CardDescription.displayName = "CardDescription"

const CardContent = React.forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement>>(({ className, ...props }, ref) => (
  <div ref={ref} className={cn("p-6 pt-0", className)} {...props} />
))
CardContent.displayName = "CardContent"

const CardFooter = React.forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement>>(({ className, ...props }, ref) => (
  <div ref={ref} className={cn("flex items-center p-6 pt-0", className)} {...props} />
))
CardFooter.displayName = "CardFooter"

export { Card, CardHeader, CardFooter, CardTitle, CardDescription, CardContent }`
        }
    ];

    for (const std of STANDARD_COMPONENTS) {
        if (!result.files.find((f: any) => f.path === std.path)) {
            result.files.push(std);
        }
    }

    // 3. DYNAMICALLY FIX IMPORTS: Replace @/ and /components-style imports with correct relative paths
    result.files = result.files.map((file: any) => {
      if (file.path.endsWith(".tsx") || file.path.endsWith(".ts")) {
        // Calculate depth relative to src/
        // src/app/page.tsx -> parts: [src, app, page.tsx] -> length 3 -> depth 1 (needs ../)
        // src/components/ui/button.tsx -> parts: [src, components, ui, button.tsx] -> length 4 -> depth 2 (needs ../../)
        
        const parts = file.path.split('/');
        const depth = parts.length - 2; // Subtract filename and src root
        
        const relativePrefix = depth > 0 ? "../".repeat(depth) : "./";
        file.content = file.content.replace(/(['"])@\//g, `$1${relativePrefix}`);
        file.content = file.content.replace(/(['"])\/(components|lib|app|hooks|store)\//g, `$1${relativePrefix}$2/`);
      }
      return file;
    });

    return NextResponse.json({ files: result.files });

  } catch (error: any) {
    console.error("Codegen Error:", error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
