
import { GeneratedFile } from './validator';

export class FallbackSystem {
  static getStaticFallback(intent: string): GeneratedFile[] {
    console.log(`[FallbackSystem] Engaging static fallback for intent: ${intent}`);
    
    // Fallback 1: Landing Page (Safe)
    if (intent.includes('landing') || intent.includes('portfolio') || intent.includes('intro')) {
      return [
        {
          path: "src/app/page.tsx",
          language: "typescript",
          content: `
import React from 'react';
import { ArrowRight, Check, Star } from 'lucide-react';

export default function LandingPage() {
  return (
    <div className="min-h-screen bg-white text-black font-sans">
      {/* Navbar */}
      <nav className="border-b border-gray-100">
        <div className="container mx-auto px-6 h-16 flex items-center justify-between">
          <div className="text-xl font-bold">Brand</div>
          <button className="bg-black text-white px-4 py-2 rounded-lg text-sm font-medium hover:bg-gray-800 transition-colors">
            Get Started
          </button>
        </div>
      </nav>

      {/* Hero */}
      <section className="py-20 px-6 text-center">
        <h1 className="text-4xl md:text-6xl font-bold mb-6 tracking-tight">
          Build something amazing.
        </h1>
        <p className="text-xl text-gray-600 mb-8 max-w-2xl mx-auto">
          This is a reliable starter template generated by Aether OS. 
          It's designed to be a safe starting point for your project.
        </p>
        <div className="flex justify-center gap-4">
          <button className="bg-black text-white px-8 py-3 rounded-full font-medium hover:bg-gray-800 transition-colors flex items-center gap-2">
            Start Now <ArrowRight size={18} />
          </button>
          <button className="bg-gray-100 text-black px-8 py-3 rounded-full font-medium hover:bg-gray-200 transition-colors">
            Learn More
          </button>
        </div>
      </section>

      {/* Features */}
      <section className="py-20 bg-gray-50">
        <div className="container mx-auto px-6 grid md:grid-cols-3 gap-8">
          {[1, 2, 3].map((i) => (
            <div key={i} className="bg-white p-6 rounded-xl shadow-sm border border-gray-100">
              <div className="w-10 h-10 bg-black text-white rounded-lg flex items-center justify-center mb-4 font-bold">
                {i}
              </div>
              <h3 className="text-xl font-bold mb-2">Feature {i}</h3>
              <p className="text-gray-600">
                This feature is ready for you to customize. Add your own content here.
              </p>
            </div>
          ))}
        </div>
      </section>
    </div>
  );
}
          `
        }
      ];
    }

    // Fallback 2: Dashboard (Safe)
    if (intent.includes('dashboard') || intent.includes('admin')) {
      return [
        {
          path: "src/app/page.tsx",
          language: "typescript",
          content: `
import React from 'react';
import { LayoutDashboard, Users, Settings, LogOut } from 'lucide-react';

export default function Dashboard() {
  return (
    <div className="min-h-screen bg-gray-50 flex">
      {/* Sidebar */}
      <aside className="w-64 bg-white border-r border-gray-200 hidden md:flex flex-col">
        <div className="h-16 flex items-center px-6 border-b border-gray-200 font-bold">
          Admin Panel
        </div>
        <nav className="p-4 space-y-1 flex-1">
          <a href="#" className="flex items-center gap-3 px-4 py-2 bg-gray-100 text-gray-900 rounded-lg text-sm font-medium">
            <LayoutDashboard size={18} /> Overview
          </a>
          <a href="#" className="flex items-center gap-3 px-4 py-2 text-gray-600 hover:bg-gray-50 rounded-lg text-sm font-medium transition-colors">
            <Users size={18} /> Users
          </a>
          <a href="#" className="flex items-center gap-3 px-4 py-2 text-gray-600 hover:bg-gray-50 rounded-lg text-sm font-medium transition-colors">
            <Settings size={18} /> Settings
          </a>
        </nav>
        <div className="p-4 border-t border-gray-200">
          <button className="flex items-center gap-3 px-4 py-2 text-red-600 hover:bg-red-50 rounded-lg text-sm font-medium w-full transition-colors">
            <LogOut size={18} /> Sign Out
          </button>
        </div>
      </aside>

      {/* Main */}
      <main className="flex-1 p-8">
        <h1 className="text-2xl font-bold mb-6">Dashboard Overview</h1>
        
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
          {[
            { label: "Total Revenue", value: "$45,231", change: "+20.1%" },
            { label: "Active Users", value: "2,350", change: "+15.2%" },
            { label: "Sales", value: "12,234", change: "+4.5%" }
          ].map((stat, i) => (
            <div key={i} className="bg-white p-6 rounded-xl border border-gray-200 shadow-sm">
              <div className="text-sm font-medium text-gray-500">{stat.label}</div>
              <div className="text-2xl font-bold mt-2">{stat.value}</div>
              <div className="text-xs text-green-600 mt-1 font-medium">{stat.change} from last month</div>
            </div>
          ))}
        </div>

        <div className="bg-white rounded-xl border border-gray-200 shadow-sm p-6 h-96 flex items-center justify-center text-gray-400">
          Chart Placeholder - Add Recharts here
        </div>
      </main>
    </div>
  );
}
          `
        }
      ];
    }

    // Default Fallback
    return [
      {
        path: "src/app/page.tsx",
        language: "typescript",
        content: `
import React from 'react';

export default function Page() {
  return (
    <div className="min-h-screen flex items-center justify-center bg-gray-50">
      <div className="text-center p-8">
        <h1 className="text-3xl font-bold mb-4">Welcome to Your App</h1>
        <p className="text-gray-600 mb-8">
          This is a generated starter template. Start editing to build your vision.
        </p>
        <button className="px-6 py-3 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors">
          Get Started
        </button>
      </div>
    </div>
  );
}
        `
      }
    ];
  }
}
