import { NextResponse } from 'next/server';
import { createRepository, pushFilesToRepo } from '@/lib/github/service';
import { createClient } from '@/lib/supabase/server';
import { createClient as createAdminClient } from '@supabase/supabase-js';

export const maxDuration = 60;

export async function POST(req: Request) {
  try {
    const { name, description, files, accessToken } = await req.json();
    
    const supabase = createClient();
    const { data: { user } } = await supabase.auth.getUser();

    if (!name) return NextResponse.json({ error: "Repo name is required" }, { status: 400 });

    // 1. Create Repo on GitHub (Storage)
    const descriptionStr = description || "Generated by Supreme Orchestrator";
    const truncatedDescription = descriptionStr.length > 300 ? descriptionStr.substring(0, 300) + "..." : descriptionStr;

    // Use User's PAT if provided, otherwise fallback to Admin PAT (Managed Service Mode)
    // For now, we assume Managed Service Mode if no accessToken, using process.env.GITHUB_PAT inside createRepository
    const repoResult = await createRepository({ 
        name, 
        description: truncatedDescription,
        private: false,
        accessToken
    });
    
    if (!repoResult.success) throw new Error(repoResult.error);
    
    const repoUrl = repoResult.url || "";
    const parts = repoUrl ? repoUrl.replace("https://github.com/", "").split("/") : ["", name];
    const repoOwner = parts[0];
    const repoName = parts[1];
    const fullRepoName = `${repoOwner}/${repoName}`;

    // 2. Push Files
    if (files && files.length > 0) {
        await new Promise(r => setTimeout(r, 2000));
        await pushFilesToRepo(
            repoOwner, 
            repoName, 
            "Initial commit by Supreme Orchestrator", 
            files,
            accessToken
        );
    }

    // 3. Save to Supabase if possible (optional)
    if (user && process.env.SUPABASE_SERVICE_ROLE_KEY && process.env.NEXT_PUBLIC_SUPABASE_URL) {
        try {
            const adminSupabase = createAdminClient(
                process.env.NEXT_PUBLIC_SUPABASE_URL!, 
                process.env.SUPABASE_SERVICE_ROLE_KEY!
            );
            const { error: dbError } = await adminSupabase.from('projects').insert({
                user_id: user.id,
                name: name,
                repo_name: fullRepoName,
                deployment_url: `https://${repoName}.vercel.app`,
                status: 'created',
                created_at: new Date().toISOString()
            });
            if (dbError) {
                console.error("Failed to save project to DB:", dbError);
            }
        } catch (e) {
            console.warn("Skipping DB insert (no service role or error).");
        }
    }

    return NextResponse.json({ 
        repoId: repoResult.id, 
        repoUrl: repoResult.url, 
        repoName: fullRepoName 
    });

  } catch (error: any) {
    console.error("Github Create Error:", error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
